# Generated by Django 5.2.6 on 2026-02-06 07:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecordkatheer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('feed_male_morning', models.FloatField(blank=True, null=True)),
                ('feed_male_morning_bundles', models.FloatField(blank=True, null=True)),
                ('feed_male_evening', models.FloatField(blank=True, null=True)),
                ('feed_male_evening_bundles', models.FloatField(blank=True, null=True)),
                ('feed_female_morning', models.FloatField(blank=True, null=True)),
                ('feed_female_morning_bundles', models.FloatField(blank=True, null=True)),
                ('feed_female_evening', models.FloatField(blank=True, null=True)),
                ('feed_female_evening_bundles', models.FloatField(blank=True, null=True)),
                ('feed_morning', models.IntegerField(blank=True, null=True)),
                ('feed_morning_bundles', models.FloatField(blank=True, null=True)),
                ('feed_evening', models.IntegerField(blank=True, null=True)),
                ('feed_evening_bundles', models.FloatField(blank=True, null=True)),
                ('water_intake', models.FloatField(blank=True, null=True)),
                ('tray_egg_morning', models.FloatField(null=True)),
                ('total_egg_morning', models.FloatField(null=True)),
                ('damaged_egg_morning', models.IntegerField(null=True)),
                ('double_egg_morning', models.IntegerField(null=True)),
                ('tray_egg_evening', models.FloatField(null=True)),
                ('total_egg_evening', models.FloatField(null=True)),
                ('damaged_egg_evening', models.IntegerField(null=True)),
                ('double_egg_evening', models.IntegerField(null=True)),
                ('artificial_insemination', models.CharField(default='No', max_length=3)),
                ('ai_hours', models.FloatField(blank=True, null=True)),
                ('ai_birds_count', models.IntegerField(blank=True, null=True)),
                ('fogger_used', models.CharField(default='No', max_length=3)),
                ('fogger_hours', models.FloatField(blank=True, null=True)),
                ('fan_used', models.CharField(default='No', max_length=3)),
                ('fan_hours', models.FloatField(blank=True, null=True)),
                ('light_used', models.CharField(default='No', max_length=3)),
                ('light_hours', models.FloatField(blank=True, null=True)),
                ('medicine', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('temperature_1', models.FloatField(blank=True, null=True)),
                ('temperature_2', models.FloatField(blank=True, null=True)),
                ('temperature_3', models.FloatField(blank=True, null=True)),
                ('temperature_4', models.FloatField(blank=True, null=True)),
                ('temperature_5', models.FloatField(blank=True, null=True)),
                ('temperature_6', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FeedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('kg', models.FloatField()),
                ('bundles', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FemaleBirdsStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_birds', models.IntegerField(default=0)),
                ('batch_start_date', models.DateField(blank=True, null=True)),
                ('batch_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10)),
                ('final_mortality', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-batch_start_date'],
            },
        ),
        migrations.CreateModel(
            name='MaleBirdsStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_birds', models.IntegerField(default=0)),
                ('batch_start_date', models.DateField(blank=True, null=True)),
                ('batch_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10)),
                ('final_mortality', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-batch_start_date'],
            },
        ),
        migrations.CreateModel(
            name='EggOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('egg_out_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='FemaleBirdsMortality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('mortality_count', models.IntegerField(default=0)),
                ('mortality_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mortality_records', to='myapp.femalebirdsstock')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MaleBirdsMortality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('mortality_count', models.IntegerField(default=0)),
                ('mortality_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mortality_records', to='myapp.malebirdsstock')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
